
HAVOC_MAX_MULT: int = 1
EXEC_TIMEOUT: int = 500
CALIBRATE_SAMPLE_SIZE: int = 3

PREFER_QUEUE_CAPACITY: int = 2000

SKIP_FUZZ_PROB: float = 0.99
SKIP_NFAV_OLD_PROB: float = 0.95
SKIP_NFAV_NEW_PROB: float = 0.75